// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Banks operations.
    /// </summary>
    public partial interface IBanks
    {
        /// <summary>
        /// 連携サービス一覧の取得
        /// </summary>
        /// <remarks>
        /// 連携しているサービス一覧を取得する
        /// </remarks>
        /// <param name='offset'>
        /// 開始位置
        /// </param>
        /// <param name='limit'>
        /// 取得上限数,最大500件
        /// </param>
        /// <param name='type'>
        /// サービス種別. Possible values include: 'bank_account', 'credit_card',
        /// 'wallet'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<BanksIndexResponse>> ListWithHttpMessagesAsync(int? offset = default(int?), int? limit = default(int?), string type = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
