/*
 * freee API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Freee.Accounting.Client.OpenAPIDateConverter;

namespace Freee.Accounting.Models
{
    /// <summary>
    /// ApprovalRequestResponse
    /// </summary>
    [DataContract(Name = "approvalRequestResponse")]
    public partial class ApprovalRequestResponse : IEquatable<ApprovalRequestResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApprovalRequestResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApprovalRequestResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApprovalRequestResponse" /> class.
        /// </summary>
        /// <param name="approvalRequest">approvalRequest (required).</param>
        public ApprovalRequestResponse(ApprovalRequestResponseApprovalRequest approvalRequest = default(ApprovalRequestResponseApprovalRequest))
        {
            // to ensure "approvalRequest" is required (not null)
            if (approvalRequest == null)
            {
                throw new ArgumentNullException("approvalRequest is a required property for ApprovalRequestResponse and cannot be null");
            }
            this.ApprovalRequest = approvalRequest;
        }

        /// <summary>
        /// Gets or Sets ApprovalRequest
        /// </summary>
        [DataMember(Name = "approval_request", IsRequired = true, EmitDefaultValue = false)]
        public ApprovalRequestResponseApprovalRequest ApprovalRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApprovalRequestResponse {\n");
            sb.Append("  ApprovalRequest: ").Append(ApprovalRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApprovalRequestResponse);
        }

        /// <summary>
        /// Returns true if ApprovalRequestResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApprovalRequestResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApprovalRequestResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ApprovalRequest == input.ApprovalRequest ||
                    (this.ApprovalRequest != null &&
                    this.ApprovalRequest.Equals(input.ApprovalRequest))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApprovalRequest != null)
                {
                    hashCode = (hashCode * 59) + this.ApprovalRequest.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
