/*
 * freee API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Freee.Accounting.Client.OpenAPIDateConverter;

namespace Freee.Accounting.Models
{
    /// <summary>
    /// ApprovalRequestResponseApprovalRequestApprovalRequestForm
    /// </summary>
    [DataContract(Name = "approvalRequestResponse_approval_request_approval_request_form")]
    public partial class ApprovalRequestResponseApprovalRequestApprovalRequestForm : IEquatable<ApprovalRequestResponseApprovalRequestApprovalRequestForm>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApprovalRequestResponseApprovalRequestApprovalRequestForm" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApprovalRequestResponseApprovalRequestApprovalRequestForm() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApprovalRequestResponseApprovalRequestApprovalRequestForm" /> class.
        /// </summary>
        /// <param name="parts">申請フォームの項目 (required).</param>
        public ApprovalRequestResponseApprovalRequestApprovalRequestForm(List<ApprovalRequestFormResponseApprovalRequestFormParts> parts = default(List<ApprovalRequestFormResponseApprovalRequestFormParts>))
        {
            // to ensure "parts" is required (not null)
            if (parts == null) {
                throw new ArgumentNullException("parts is a required property for ApprovalRequestResponseApprovalRequestApprovalRequestForm and cannot be null");
            }
            this.Parts = parts;
        }

        /// <summary>
        /// 申請フォームの項目
        /// </summary>
        /// <value>申請フォームの項目</value>
        [DataMember(Name = "parts", IsRequired = true, EmitDefaultValue = false)]
        public List<ApprovalRequestFormResponseApprovalRequestFormParts> Parts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApprovalRequestResponseApprovalRequestApprovalRequestForm {\n");
            sb.Append("  Parts: ").Append(Parts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApprovalRequestResponseApprovalRequestApprovalRequestForm);
        }

        /// <summary>
        /// Returns true if ApprovalRequestResponseApprovalRequestApprovalRequestForm instances are equal
        /// </summary>
        /// <param name="input">Instance of ApprovalRequestResponseApprovalRequestApprovalRequestForm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApprovalRequestResponseApprovalRequestApprovalRequestForm input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Parts == input.Parts ||
                    this.Parts != null &&
                    input.Parts != null &&
                    this.Parts.SequenceEqual(input.Parts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Parts != null)
                {
                    hashCode = (hashCode * 59) + this.Parts.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
