/*
 * freee API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Freee.Accounting.Client.OpenAPIDateConverter;

namespace Freee.Accounting.Models
{
    /// <summary>
    /// ApprovalFlowRouteResponse
    /// </summary>
    [DataContract(Name = "approvalFlowRouteResponse")]
    public partial class ApprovalFlowRouteResponse : IEquatable<ApprovalFlowRouteResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApprovalFlowRouteResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApprovalFlowRouteResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApprovalFlowRouteResponse" /> class.
        /// </summary>
        /// <param name="approvalFlowRoute">approvalFlowRoute (required).</param>
        public ApprovalFlowRouteResponse(ApprovalFlowRouteResponseApprovalFlowRoute approvalFlowRoute = default(ApprovalFlowRouteResponseApprovalFlowRoute))
        {
            // to ensure "approvalFlowRoute" is required (not null)
            if (approvalFlowRoute == null) {
                throw new ArgumentNullException("approvalFlowRoute is a required property for ApprovalFlowRouteResponse and cannot be null");
            }
            this.ApprovalFlowRoute = approvalFlowRoute;
        }

        /// <summary>
        /// Gets or Sets ApprovalFlowRoute
        /// </summary>
        [DataMember(Name = "approval_flow_route", IsRequired = true, EmitDefaultValue = false)]
        public ApprovalFlowRouteResponseApprovalFlowRoute ApprovalFlowRoute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApprovalFlowRouteResponse {\n");
            sb.Append("  ApprovalFlowRoute: ").Append(ApprovalFlowRoute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApprovalFlowRouteResponse);
        }

        /// <summary>
        /// Returns true if ApprovalFlowRouteResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApprovalFlowRouteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApprovalFlowRouteResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ApprovalFlowRoute == input.ApprovalFlowRoute ||
                    (this.ApprovalFlowRoute != null &&
                    this.ApprovalFlowRoute.Equals(input.ApprovalFlowRoute))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApprovalFlowRoute != null)
                {
                    hashCode = (hashCode * 59) + this.ApprovalFlowRoute.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
