// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DealsRenews
    {
        /// <summary>
        /// Initializes a new instance of the DealsRenews class.
        /// </summary>
        public DealsRenews()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DealsRenews class.
        /// </summary>
        /// <param name="id">+更新行ID</param>
        /// <param name="updateDate">更新日 (yyyy-mm-dd)</param>
        /// <param name="renewTargetId">+更新の対象行ID</param>
        /// <param name="renewTargetType">+更新の対象行タイプ. Possible values include:
        /// 'detail', 'accrual', 'renew'</param>
        /// <param name="details">+更新の明細行一覧（配列）</param>
        public DealsRenews(int id, string updateDate, int renewTargetId, string renewTargetType, IList<DealsRenewsDetailsItem> details)
        {
            Id = id;
            UpdateDate = updateDate;
            RenewTargetId = renewTargetId;
            RenewTargetType = renewTargetType;
            Details = details;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets +更新行ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets 更新日 (yyyy-mm-dd)
        /// </summary>
        [JsonProperty(PropertyName = "update_date")]
        public string UpdateDate { get; set; }

        /// <summary>
        /// Gets or sets +更新の対象行ID
        /// </summary>
        [JsonProperty(PropertyName = "renew_target_id")]
        public int RenewTargetId { get; set; }

        /// <summary>
        /// Gets or sets +更新の対象行タイプ. Possible values include: 'detail',
        /// 'accrual', 'renew'
        /// </summary>
        [JsonProperty(PropertyName = "renew_target_type")]
        public string RenewTargetType { get; set; }

        /// <summary>
        /// Gets or sets +更新の明細行一覧（配列）
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IList<DealsRenewsDetailsItem> Details { get; set; }

    }
}
