// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DealsIndexResponse
    {
        /// <summary>
        /// Initializes a new instance of the DealsIndexResponse class.
        /// </summary>
        public DealsIndexResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DealsIndexResponse class.
        /// </summary>
        public DealsIndexResponse(IList<Deals> deals, DealsIndexResponseMeta meta)
        {
            Deals = deals;
            Meta = meta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deals")]
        public IList<Deals> Deals { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meta")]
        public DealsIndexResponseMeta Meta { get; set; }

    }
}
