// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class JournalsStatusResponseJournals
    {
        /// <summary>
        /// Initializes a new instance of the JournalsStatusResponseJournals
        /// class.
        /// </summary>
        public JournalsStatusResponseJournals()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JournalsStatusResponseJournals
        /// class.
        /// </summary>
        /// <param name="id">受け付けID</param>
        /// <param name="companyId">事業所ID</param>
        /// <param name="downloadType">ダウンロード形式. Possible values include:
        /// 'csv', 'generic', 'pdf'</param>
        /// <param name="status">事業所ID. Possible values include: 'enqueued',
        /// 'working', 'uploaded', 'failed'</param>
        /// <param name="startDate">取得開始日 (yyyy-mm-dd)</param>
        /// <param name="endDate">取得終了日 (yyyy-mm-dd)</param>
        /// <param name="downloadUrl">ダウンロードURL</param>
        public JournalsStatusResponseJournals(int id, int companyId, string downloadType, string status, string startDate, string endDate, IList<string> visibleTags, string downloadUrl = default(string))
        {
            Id = id;
            CompanyId = companyId;
            DownloadType = downloadType;
            Status = status;
            StartDate = startDate;
            EndDate = endDate;
            VisibleTags = visibleTags;
            DownloadUrl = downloadUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets 受け付けID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets 事業所ID
        /// </summary>
        [JsonProperty(PropertyName = "company_id")]
        public int CompanyId { get; set; }

        /// <summary>
        /// Gets or sets ダウンロード形式. Possible values include: 'csv', 'generic',
        /// 'pdf'
        /// </summary>
        [JsonProperty(PropertyName = "download_type")]
        public string DownloadType { get; set; }

        /// <summary>
        /// Gets or sets 事業所ID. Possible values include: 'enqueued', 'working',
        /// 'uploaded', 'failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets 取得開始日 (yyyy-mm-dd)
        /// </summary>
        [JsonProperty(PropertyName = "start_date")]
        public string StartDate { get; set; }

        /// <summary>
        /// Gets or sets 取得終了日 (yyyy-mm-dd)
        /// </summary>
        [JsonProperty(PropertyName = "end_date")]
        public string EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "visible_tags")]
        public IList<string> VisibleTags { get; set; }

        /// <summary>
        /// Gets or sets ダウンロードURL
        /// </summary>
        [JsonProperty(PropertyName = "download_url")]
        public string DownloadUrl { get; set; }

    }
}
