// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SegmentTagParams
    {
        /// <summary>
        /// Initializes a new instance of the SegmentTagParams class.
        /// </summary>
        public SegmentTagParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SegmentTagParams class.
        /// </summary>
        /// <param name="companyId">事業所ID</param>
        /// <param name="name">セグメントタグ</param>
        /// <param name="description">備考</param>
        /// <param name="shortcut1">ショートカット１ (20文字以内)</param>
        /// <param name="shortcut2">ショートカット２ (20文字以内)</param>
        public SegmentTagParams(int companyId, string name, string description = default(string), string shortcut1 = default(string), string shortcut2 = default(string))
        {
            CompanyId = companyId;
            Name = name;
            Description = description;
            Shortcut1 = shortcut1;
            Shortcut2 = shortcut2;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets 事業所ID
        /// </summary>
        [JsonProperty(PropertyName = "company_id")]
        public int CompanyId { get; set; }

        /// <summary>
        /// Gets or sets セグメントタグ
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets 備考
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets ショートカット１ (20文字以内)
        /// </summary>
        [JsonProperty(PropertyName = "shortcut1")]
        public string Shortcut1 { get; set; }

        /// <summary>
        /// Gets or sets ショートカット２ (20文字以内)
        /// </summary>
        [JsonProperty(PropertyName = "shortcut2")]
        public string Shortcut2 { get; set; }

    }
}
