// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TaxesIndexResponseTaxesItem
    {
        /// <summary>
        /// Initializes a new instance of the TaxesIndexResponseTaxesItem
        /// class.
        /// </summary>
        public TaxesIndexResponseTaxesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaxesIndexResponseTaxesItem
        /// class.
        /// </summary>
        /// <param name="id">税区分ID</param>
        /// <param name="name">税区分</param>
        public TaxesIndexResponseTaxesItem(int id, string name)
        {
            Id = id;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets 税区分ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets 税区分
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
