// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TrialPlSectionsResponseTrialPlSectionsBalancesItemSectionsItemPartnersItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TrialPlSectionsResponseTrialPlSectionsBalancesItemSectionsItemPartnersItem
        /// class.
        /// </summary>
        public TrialPlSectionsResponseTrialPlSectionsBalancesItemSectionsItemPartnersItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TrialPlSectionsResponseTrialPlSectionsBalancesItemSectionsItemPartnersItem
        /// class.
        /// </summary>
        /// <param name="id">取引先ID</param>
        /// <param name="name">取引先名</param>
        /// <param name="closingBalance">期末残高</param>
        public TrialPlSectionsResponseTrialPlSectionsBalancesItemSectionsItemPartnersItem(int id, string name = default(string), int? closingBalance = default(int?))
        {
            Id = id;
            Name = name;
            ClosingBalance = closingBalance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets 取引先ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets 取引先名
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets 期末残高
        /// </summary>
        [JsonProperty(PropertyName = "closing_balance")]
        public int? ClosingBalance { get; set; }

    }
}
