// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UsersMeResponseUser
    {
        /// <summary>
        /// Initializes a new instance of the UsersMeResponseUser class.
        /// </summary>
        public UsersMeResponseUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UsersMeResponseUser class.
        /// </summary>
        /// <param name="id">ユーザーID</param>
        /// <param name="email">メールアドレス</param>
        /// <param name="displayName">表示ユーザー名</param>
        /// <param name="firstName">名</param>
        /// <param name="lastName">姓</param>
        /// <param name="firstNameKana">名（カナ）</param>
        /// <param name="lastNameKana">姓（カナ）</param>
        public UsersMeResponseUser(int id, string email, string displayName = default(string), string firstName = default(string), string lastName = default(string), string firstNameKana = default(string), string lastNameKana = default(string), IList<UsersMeResponseUserCompaniesItem> companies = default(IList<UsersMeResponseUserCompaniesItem>))
        {
            Id = id;
            Email = email;
            DisplayName = displayName;
            FirstName = firstName;
            LastName = lastName;
            FirstNameKana = firstNameKana;
            LastNameKana = lastNameKana;
            Companies = companies;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets ユーザーID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets メールアドレス
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets 表示ユーザー名
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets 名
        /// </summary>
        [JsonProperty(PropertyName = "first_name")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets 姓
        /// </summary>
        [JsonProperty(PropertyName = "last_name")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets 名（カナ）
        /// </summary>
        [JsonProperty(PropertyName = "first_name_kana")]
        public string FirstNameKana { get; set; }

        /// <summary>
        /// Gets or sets 姓（カナ）
        /// </summary>
        [JsonProperty(PropertyName = "last_name_kana")]
        public string LastNameKana { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companies")]
        public IList<UsersMeResponseUserCompaniesItem> Companies { get; set; }

    }
}
