// <auto-generated>
// Copyright (c) freee K.K. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license
// information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
//
// </auto-generated>

namespace Freee.Accounting.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WalletablesIndexResponseWalletablesItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// WalletablesIndexResponseWalletablesItem class.
        /// </summary>
        public WalletablesIndexResponseWalletablesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// WalletablesIndexResponseWalletablesItem class.
        /// </summary>
        /// <param name="id">口座ID</param>
        /// <param name="name">口座名 (255文字以内)</param>
        /// <param name="bankId">サービスID</param>
        /// <param name="type">口座区分 (銀行口座: bank_account, クレジットカード: credit_card,
        /// 現金: wallet). Possible values include: 'bank_account',
        /// 'credit_card', 'wallet'</param>
        /// <param name="walletableBalance">登録残高</param>
        /// <param name="lastBalance">同期残高</param>
        public WalletablesIndexResponseWalletablesItem(int id, string name, int? bankId, string type, int? walletableBalance = default(int?), int? lastBalance = default(int?))
        {
            Id = id;
            Name = name;
            BankId = bankId;
            Type = type;
            WalletableBalance = walletableBalance;
            LastBalance = lastBalance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets 口座ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets 口座名 (255文字以内)
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets サービスID
        /// </summary>
        [JsonProperty(PropertyName = "bank_id")]
        public int? BankId { get; set; }

        /// <summary>
        /// Gets or sets 口座区分 (銀行口座: bank_account, クレジットカード: credit_card, 現金:
        /// wallet). Possible values include: 'bank_account', 'credit_card',
        /// 'wallet'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets 登録残高
        /// </summary>
        [JsonProperty(PropertyName = "walletable_balance")]
        public int? WalletableBalance { get; set; }

        /// <summary>
        /// Gets or sets 同期残高
        /// </summary>
        [JsonProperty(PropertyName = "last_balance")]
        public int? LastBalance { get; set; }

    }
}
